### ISSUE TITLE
Ark Server

### ISSUE THREAD

**Issue by Hantse** [Challengermode/CoreRcon#7]
Hello,

I try a simple call for Ark Server, but i receive no response :

`
class Program
{
       static async Task Main(string[] args)
        {
            var rcon = new RCON(IPAddress.Parse("my.server.ip"), 32330, "mypasswordadmin");
            await rcon.ConnectAsync();
            var players = await rcon.SendCommandAsync("listplayers");
            Console.ReadKey();
        }
    }
`

No error, no exception, just block without any response.

I can connect on RCON with other tools.

Any idea ?

**Comment by xobust** [comment]
Hi, I found the problem. 
It seems to be because the ark server cannot handle concurrent calls well. 
The "listplayers" command is run concurrently with a beacon message. 
You can fix this by disabeling beacons `RCON(IPAddress.Parse("my.server.ip"),` 32330, "mypasswordadmin", 0);`

I'm considering disabling beacons by default as I don't think that they are necessary.

**Comment by Hantse** [comment]
Hello,

Indeed, with this solution i can connect.

Thank for fast support :)

Kind regards,
